### input
kafka.input.consumer.offsets.topic.name=__consumer_offsets
kafka.input.bootstrap.servers=localhost:9094
kafka.input.consumer.group.name=kafka.lag-streamer
kafka.input.bootstrap.servers.timeout.ms=30000
kafka.input.partition.metadata.update.interval.ms=10000

### outputs
kafka.output.enabled=true
kafka.output.consumer.lags.topic.name=consumer.lags
kafka.output.bootstrap.servers=localhost:9094
kafka.output.bootstrap.servers.timeout.ms=30000

### logging
kafkajs.logLevel=WARN
